### PR TITLE
feat/better-interface (navigable info, one line per day,configurable overlaps and clocks)

### PR DESCRIPTION
**Pull request by aizensoosuke**
Built on top of #11.

Implements following improvements:

- Navigable info line (left click jumps to file).
- Blocks are displayed on the right day line. Each day has one (or several, see next items) dedicated lines.
- Configurable overlaps (either on new lines, or with a different warning face).
- Configurable clocks (either not displayed, or on a dedicated line beginning with "$", or in the same line as other events).

I have taken some inspiration from [deopurkar's fork](https://github.com/deopurkar/org-timeline/commits/master).

That's the result: 
image

Monday has a clock item, Thursday has overlapping items. All blocks are interactive. Everything is configurable.

### CODE REVIEW

**Comment by aizensoosuke** [comment]
Commits b0dcaaf (feat: show info for nearest block) and next ones shouldn't appear here. I pushed to the wrong branch and can't seem to remove them from this branch's history.

**Comment by aizensoosuke** [comment]
> For the other work in #16 and #17, you can do a rebase on the origin/master to re-use the work which has already been merged. 

This should be done, now. Hopefully I didn't do any mistake (I skipped all conflicts when rebasing).

**Comment by aizensoosuke** [comment]
So, I don't really know what happens when I rebase and skip the conflicts. But I rebased on #17 after copying it to a new branch, and I definitely lost part of the code (whole functions) doing that. I don't know what I did wrong, I thought skipping conflicts just kept the version on the current branch. Is there something you know I should do differently?

**Comment by Fuco1** [comment]
> So, I don't really know what happens when I rebase and skip the conflicts. But I rebased on #17 after copying it to a new branch, and I definitely lost part of the code (whole functions) doing that. I don't know what I did wrong, I thought skipping conflicts just kept the version on the current branch. Is there something you know I should do differently?

When there are conflicts, they usually need to be resolved.  What that means is that two commits changed the same line of code and you have to pick which version is the correct one (as git can not know your or your colleagues intentions).

It is my fault that this happens because I reordered some commits on the main branch.  I will deal with it.  If you have all the code necessary on this branch (i.e. what was merged in #11), then just continue  pushing code here and I'll wrap it up in the end.  Dealing with messy rebases is a bit too annoying even for seasoned git users.  I don't even know where to point you as the documentation is quite terse and git itself is very user-unfriendly :D It's years of trial and error mostly.

If the work here is done, then mark it as requesting review (on the top right in the menu you can set me as reviewer) and I'll review and merge it or give you feedback.

Now that you are better with git this probably won't happen very often, but it's not uncommon for one contributor to mess up the branch for another, sorry for that :blush:

**Comment by Fuco1** [comment]
> and I definitely lost part of the code (whole functions) doing that

Did you actually lose it or it was only lost during the rebase?  If it is completely gone, we can still revive it using something called `git reflog`, but that is quite complicated, so it would be best for you to zip your repository  (locally) and send it to me so I can hopefully recover the lost code.

**Comment by Fuco1** [comment]
I invited you as a collaborator, so you can manage all the issues on the project and push the code directly to this repository (i.e. you won't have to use your fork).  However, you can keep using a fork if you feel safer that way, it doesn't really matter. 

It would still be good to contribute through the pull request system in the beginning so we can do reviews easily.

**Comment by aizensoosuke** [comment]
> > and I definitely lost part of the code (whole functions) doing that
> 
> Did you actually lose it or it was only lost during the rebase? If it is completely gone, we can still revive it using something called `git reflog`, but that is quite complicated, so it would be best for you to zip your repository (locally) and send it to me so I can hopefully recover the lost code.

My phrasing wasn't clear at all, but I made a backup of branch #17 before rebasing (I wanted to be sure not to lose the last version of my code). So it's all fine, I just did a reset with my backup. 

Since I finalized the rebase on this PR (#16) and didn't do a backup, I hope no code was lost. But #17 is the latest version anyway, so any changes made by #17 should have priority over #16.

> I don't even know where to point you as the documentation is quite terse and git itself is very user-unfriendly :D It's years of trial and error mostly.

Yeah it all feels quite messy for now, but it does seem like it can be very powerful when you know what you're doing.

**Comment by aizensoosuke** [comment]
> I invited you as a collaborator, so you can manage all the issues on the project and push the code directly to this repository (i.e. you won't have to use your fork). However, you can keep using a fork if you feel safer that way, it doesn't really matter.
> 
> It would still be good to contribute through the pull request system in the beginning so we can do reviews easily.

Neat, thanks! I'll keep using my fork yes, I'm definitely not experienced enough with git to do things more directly.

**Comment by Fuco1** [comment]
> Since I finalized the rebase on this PR (#16) and didn't do a backup, I hope no code was lost. But #17 is the latest version anyway, so any changes made by #17 should have priority over #16.

So does this mean we can actually close this one as all the changes are also on #17?

**Comment by aizensoosuke** [comment]
> So does this mean we can actually close this one as all the changes are also on #17?

Definitely, I was just dividing new features into several PRs but you can directly jump to #17.

**Comment by aizensoosuke** [comment]
I edited the description of #17 to include the new features from here. You can directly review #17.

**Comment by Fuco1** [comment]
If there are changes which build upon features from a different pull request, what can be done is to point the new PR towards the other branch, then it will only show the changes against that code.  But for that, it needs to be in one repository.

Hit EDIT: 
screen1024

Then select the branch:

screen1027

The GIT structure will look something like this (see log).  You would then in github say that `feat/b` should be merged into `feat/a`.  However, every time `feat/a` would be updated, `feat/b` branch would also need to be rebased on top of `feat/a` to contain the changes there.

```shell
[13:37:16]matus@thales:~/test/git-test
> git init
Initialized empty Git repository in /home/matus/test/git-test/.git/
[13:37:17]matus@thales:~/test/git-test
> touch a b c d readme file other
[13:37:21]matus@thales:~/test/git-test
> git add readme
[13:37:23]matus@thales:~/test/git-test
> git commit -m "feat: initial commit"
[master (root-commit) 5d1ba96] feat: initial commit
 1 file changed, 0 insertions(+), 0 deletions(-)
 create mode 100644 readme
[13:37:31]matus@thales:~/test/git-test
> git add other file
[13:37:34]matus@thales:~/test/git-test
> git commit -m "feat: other files"
[master 5d1eb54] feat: other files
 2 files changed, 0 insertions(+), 0 deletions(-)
 create mode 100644 file
 create mode 100644 other
[13:37:42]matus@thales:~/test/git-test
> git checkout -b feat/a
Switched to a new branch 'feat/a'
[13:37:49]matus@thales:~/test/git-test
> git add a
[13:37:51]matus@thales:~/test/git-test
> git commit -m "feat(A): a"
[feat/a abf4ec3] feat(A): a
 1 file changed, 0 insertions(+), 0 deletions(-)
 create mode 100644 a
[13:37:57]matus@thales:~/test/git-test
> git add b
[13:37:58]matus@thales:~/test/git-test
> git commit -m "feat(A): b"
[feat/a f0b0dd3] feat(A): b
 1 file changed, 0 insertions(+), 0 deletions(-)
 create mode 100644 b
[13:38:00]matus@thales:~/test/git-test
> git checkout -b feat/b
Switched to a new branch 'feat/b'
[13:38:04]matus@thales:~/test/git-test
> git add c
[13:38:07]matus@thales:~/test/git-test
> git commit -m "feat(B): c"
[feat/b f299f2c] feat(B): c
 1 file changed, 0 insertions(+), 0 deletions(-)
 create mode 100644 c
[13:38:13]matus@thales:~/test/git-test
> git add d
[13:38:15]matus@thales:~/test/git-test
> git commit -m "feat(B): d"
[feat/b dc4cc67] feat(B): d
 1 file changed, 0 insertions(+), 0 deletions(-)
 create mode 100644 d
[13:38:16]matus@thales:~/test/git-test
> git lol
* dc4cc67 (HEAD -> feat/b) feat(B): d
* f299f2c feat(B): c
* f0b0dd3 (feat/a) feat(A): b
* abf4ec3 feat(A): a
* 5d1eb54 (master) feat: other files
* 5d1ba96 feat: initial commit
[13:38:37]matus@thales:~/test/git-test
> git checkout feat/a
Switched to branch 'feat/a'
[13:38:41]matus@thales:~/test/git-test
> touch e
[13:38:44]matus@thales:~/test/git-test
> git add e
[13:38:46]matus@thales:~/test/git-test
> git commit -m "feat(A): e"
[feat/a cf9ab43] feat(A): e
 1 file changed, 0 insertions(+), 0 deletions(-)
 create mode 100644 e
[13:38:52]matus@thales:~/test/git-test
> git lol
* cf9ab43 (HEAD -> feat/a) feat(A): e
| * dc4cc67 (feat/b) feat(B): d
| * f299f2c feat(B): c
|/
* f0b0dd3 feat(A): b
* abf4ec3 feat(A): a
* 5d1eb54 (master) feat: other files
* 5d1ba96 feat: initial commit
[13:38:53]matus@thales:~/test/git-test
> git checkout feat/b
Switched to branch 'feat/b'
[13:39:00]matus@thales:~/test/git-test
> git rebase feat/a
First, rewinding head to replay your work on top of it...
Applying: feat(B): c
Applying: feat(B): d
[13:39:05]matus@thales:~/test/git-test
> git lol
* 9fc6894 (HEAD -> feat/b) feat(B): d
* ebb632b feat(B): c
* cf9ab43 (feat/a) feat(A): e
* f0b0dd3 feat(A): b
* abf4ec3 feat(A): a
* 5d1eb54 (master) feat: other files
* 5d1ba96 feat: initial commit
[13:39:06]matus@thales:~/test/git-test
>
```

**Comment by Fuco1** [comment]
(`git lol` is an alias for `lol = log --oneline --decorate --all --graph`, you can set aliases: `git config --global alias.lol 'log --oneline --decorate --all --graph'`.  I find this one rather useful)

**Comment by aizensoosuke** [comment]
> If there are changes which build upon features from a different pull request, what can be done is to point the new PR towards the other branch, then it will only show the changes against that code. But for that, it needs to be in one repository.

> The GIT structure will look something like this (see log). You would then in github say that `feat/b` should be merged into `feat/a`. However, every time `feat/a` would be updated, `feat/b` branch would also need to be rebased on top of `feat/a` to contain the changes there.

Okay got it, thanks a lot for that.

**Pull request closed without merging**
